--Añade los indices a la tabla ACCOUNTS
EXEC SP_ADD_INDEX_IN 'ACCOUNTS', 'USERNAME|CREATE_DATE|ROL_ID|ACCOUNT_TYPE'

--Añade los indices a la tabla GAMES
EXEC SP_ADD_INDEX_IN 'GAMES', 'PRICE|CREATED_DATE'

--Lo mismo pero con TRANSACTIONS
EXEC SP_ADD_INDEX_IN 'TRANSACTIONS', 'TRANS_DATE'

--Lo mismo
EXEC SP_ADD_INDEX_IN 'VOTES', 'VOTE_TYPE'
