INSERT INTO PERMISSIONS (PER_NAME, PER_DESCRIPTION) VALUES
('see_players', 'Can see other profiles'),
('remove_users', 'Can remove users'),
('buy_games', 'Can Buy Games'),
('add_vote', 'Can vote in games'),
('remove_his_vote', 'Can remove his vote'),
('edit_his_vote', 'Can edit his vote'),
('remove_another_votes', 'Can remove votes of other people'),
('add_his_games', 'Can sell his games in the shop'),
('edit_his_games', 'Can edit his games'),
('remove_his_games', 'Can remove his games from the shop'),
('remove_another_games', 'Can remove another games from the shop'),
('add_his_achievements', 'Can add achievements in his games'),
('remove_his_achievements', 'Can remove achievements in his games'),
('unlock_his_achievements', 'Can unlock achievements in his games'),
('remove_another_achievements', 'Can remove another achievements from the shop'),
('unlock_another_achievements', 'Can unlock achievements in any game'),
('get_his_game', 'Can get free any game in the shop'),
('get_another_games', 'Can get free another game in the shop'),
('get_his_games_to_people', 'Can give free his games in the shop to another people'),
('get_another_games_to_people', 'Can give free any game in the shop to another people'),
('unget_his_games', 'Can remove games from his bookstore'),
('unget_his_games_to_people', 'Can remove games from bookstores of the other people'),
('unget_another_games_to_people', 'Can remove games from the bookstore of the other people'),
('add_games_genders', 'Can add new games genders'),
('edit_games_genders', 'Can edit games genders'),
('remove_games_genders', 'Can remove games genders'),
('add_roles', 'Can add new roles'),
('edit_roles', 'Can edit roles'),
('remove_roles', 'Can remove roles'),
('add_new_admins', 'Can add new admin'),
('remove_another_admins', 'Can remove another admins')

INSERT INTO ROLES (ROL_NAME, OBLIGATORY) VALUES
('USER', 1),
('DEVELOPER', 0),
('ADMINISTRATOR', 0),
('SUPER_ADMIN', 0)

--TODO: Eliminarle la capacidad de agregar juegos a la tienda

INSERT INTO ROLES_PERMISSIONS (ROL_ID, PER_ID) VALUES
(1,  1),
(1,  3),
(1,  4),
(1,  5),
(1,  6),
(2,  1),
(2,  8),
(2,  9),
(2,  10),
(2,  12),
(2, 13),
(2,  14),
(2,  17),
(2,  19),
(2,  21),
(2, 22),
(3, 2),
(3, 7),
(3, 11),
(3, 15),
(3, 23),
(3, 24),
(3, 25),
(3, 26),
(3, 27),
(3, 28),
(3, 29),
(4, 16),
(4, 18),
(4, 20),
(4, 30),
(4, 31)